// assets/src/App.vue
<template>
  <div id="app">
    <nav id="navbar" class="navbar has-shadow is-spaced" role="navigation" aria-label="main navigation">
      <div class="container">
        <div class="navbar-brand">
          <a class="navbar-item">
            <img src="./assets/mgp.png" alt="MGP Logo">
          </a>

          <a role="button" class="navbar-burger" aria-label="menu" aria-expanded="false">
            <span aria-hidden="true"></span>
            <span aria-hidden="true"></span>
            <span aria-hidden="true"></span>
          </a>
        </div>

        <div class="navbar-menu">
          <div class="navbar-start">
            <router-link to="/" class="navbar-item">Home</router-link>
            <router-link to="/products" class="navbar-item">Products</router-link>
            <router-link to="/invoices" class="navbar-item">Invoices</router-link>
            <router-link to="/customers" class="navbar-item">Customers</router-link>
            <router-link to="/pdcs" class="navbar-item">Pdcs</router-link>
            <router-link to="/reports" class="navbar-item">Reports</router-link>
          </div>

          <div class="navbar-end">
            <a class="navbar-item" @click="logout">Logout</a>
          </div>
        </div>

      </div>
    </nav>
    <router-view/>
  </div>
</template>
<script>
export default {
  methods: {
    logout() {
      fetch
        .delete("/api/sessions", {
          method: "delete",
          withCredentials: false
        })
        .then(function(response) {
          console.log(response);
          window.location.replace("/");
        })
        .catch(function(error) {
          console.log(error);
        });
    }
  }
};
</script>
<style lang="scss">
// Import Bulma's core
@import "~bulma/sass/utilities/_all";

// Customize Bulma variables here

// Import Bulma and Buefy styles
@import "~bulma";
@import "~buefy/src/scss/buefy";

#app {
  /* -webkit-font-smoothing: antialiased;
  -moz-osx-font-smoothing: grayscale;
  font-family: "Avenir", Helvetica, Arial, sans-serif;
  text-align: center;
  color: #2c3e50;
  */
}

#navbar {
  padding: 0;
}

.navbar-start a.router-link-exact-active {
  color: $red;
}

section.section {
  padding-top: 1rem;
}
</style>

// assets/js/App.svelte
<script>
  import router, { page } from './router'
  import { path } from './stores/path'

  let navMenuOpen = false


  function toggleNavMenu() {
    navMenuOpen = !navMenuOpen
  }

  router.start()
</script>

<nav
  id="navbar"
  class="navbar is-transparent is-fixed-top is-spaced"
  role="navigation"
  aria-label="main navigation"
>
  <div class="container">
    <div class="navbar-brand">
      <a class="navbar-item" href="#logo">
        <img src="/images/mgp.png" alt="MGP Logo"/>
      </a>
      <a
        role="button"
        class="navbar-burger"
        class:is-active="{navMenuOpen}"
        aria-label="menu"
        aria-expanded="false"
        href="#menu"
        on:click="{() => toggleNavMenu()}"
      >
        <span aria-hidden="true"></span>
        <span aria-hidden="true"></span>
        <span aria-hidden="true"></span>
      </a>
    </div>
    <div class="navbar-menu" class:is-active="{navMenuOpen}" on:click="{() => toggleNavMenu()}">
      <div class="navbar-start">
        <a class="navbar-item" href="/" class:is-active="{$path == '/'}">Home</a>
        <a class="navbar-item" href="/products" class:is-active="{$path == '/products'}">Products</a>
        <a class="navbar-item" href="/sales" class:is-active="{$path.startsWith('/sales')}">Sales</a>
        <a class="navbar-item" href="/invoices" class:is-active="{$path == '/invoices'}">Invoices</a>
        <a class="navbar-item" href="/customers" class:is-active="{$path == '/customers'}">Customers</a>
        <a class="navbar-item" href="/pdcs" class:is-active="{$path == '/pdcs'}">Pdcs</a>
        <a class="navbar-item" href="/payroll" class:is-active="{$path == '/payroll'}">Payroll</a>
      </div>
      <div class="navbar-end">
        <a class="navbar-item" @click="logout" href="#logout">Logout</a>
      </div>
    </div>
  </div>
</nav>
<svelte:component this={$page.component} {...$page.props} />
