// assets/src/views/Customers.vue
<template>
  <section class="section">
    <div class="container">
      <BField>
        <p class="control">
          <button class="button is-static">
            Search Customer
          </button>
        </p>
        <BAutocomplete
          expanded
          v-model="name"
          :data="customers"
          placeholder="e.g. 37 Chemists"
          autofocus
          icon="person"
          field="description"
          :loading="isFetching"
          @input="getAsyncCustomers"
          @select="option => fetchSelectedCustomer(option)"
          >
          <template slot-scope="props">
            <div class="media">
              <div class="media-content">
                {{ props.option.description }}
                <br>
                <small>
                  <b>{{ props.option.id }}</b>,
                  <b>{{ props.option.region }}</b>,
                  <b>{{ props.option.is_gov }}</b>,
                  <b>{{ props.option.resp }}</b>
                </small>
              </div>
            </div>
          </template>
          <template slot="empty">No results found</template>
        </BAutocomplete>
        <BSelect placeholder="Fin Year" v-model="year" @input="yearChanged">
          <option
            v-for="option in fin_years"
            :value="option"
            :key=option>
          {{option}}
          </option>
        </BSelect>
      </BField>
    </div>

    <div v-if="postings.op_bal != null" class="section" style="padding-top: 1rem; padding-bottom: 1rem;">
      <div class="container">
        <div class="columns">
          <div class="column">
            <h1 class="title">
              {{postings.description}}
            </h1>
            <h2 class="subtitle">
              <BTaglist>
                <BTag>{{postings.id}}</BTag>
                <BTag>{{postings.region}}</BTag>
                <BTag>{{postings.is_gov}}</BTag>
                <BTag>{{postings.resp}}</BTag>
              </BTaglist>
            </h2>
          </div>
        </div>
        <table class="table is-narrow is-fullwidth is-hoverable">
          <tbody>
            <tr>
              <td></td>
              <td></td>
              <td></td>
              <td></td>
              <th class="has-text-right">Opening Bal:</th>
              <th class="has-text-right">{{postings.op_bal | currency('')}}</th>
            </tr>
            <tr>
              <td></td>
              <td></td>
              <td></td>
              <td></td>
              <td></td>
              <td></td>
            </tr>
            <tr class="underline">
              <th>ID</th>
              <th>Date</th>
              <th>Description</th>
              <th class="has-text-right">Debit</th>
              <th class="has-text-right">Credit</th>
              <th class="has-text-right">Balance</th>
            </tr>
            <tr v-for="p in postings.postings" :key="p.id">
              <td>
                <span v-if="p.id.startsWith('S')">{{p.id}}</span>
                <span v-else>{{p.id.substring(8, p.id.length)}}</span>
              </td>
              <td>{{p.date}}</td>
              <td>{{p.description}}</td>
              <td class="has-text-right">{{p.debit | currency('')}}</td>
              <td class="has-text-right">{{p.credit | currency('')}}</td>
              <td class="has-text-right">{{p.bal | currency('')}}</td>
            </tr>
            <tr class="underline overline">
              <td></td>
              <td></td>
              <th class="has-text-right">Total: </th>
              <th class="has-text-right">{{postings.total_debit | currency('')}}</th>
              <th class="has-text-right">{{postings.total_credit | currency('')}}</th>
              <th class="has-text-right">
              {{postings.total_bal | currency('') }}
              </th>
            </tr>
            <tr>
              <td></td>
              <td></td>
              <td></td>
              <td></td>
              <td></td>
              <td></td>
            </tr>
            <tr class="underline" v-if="postings.total_pdcs > 0">
              <th>PDCS</th>
              <td></td>
              <td></td>
              <td></td>
              <td></td>
              <td></td>
            </tr>
            <tr v-for="p in postings.pdcs" :key="p.id">
              <td>{{p.id}}</td>
              <td>{{p.date}}</td>
              <td>{{p.cheque}}</td>
              <td></td>
              <td class="has-text-right">{{p.amount | currency('')}}</td>
              <td></td>
            </tr>
            <tr class="underline overline" v-if="postings.total_pdcs > 0">
              <td></td>
              <td></td>
              <th class="has-text-right">Total: </th>
              <th class="has-text-right"></th>
              <th class="has-text-right">{{postings.total_pdcs | currency('')}}</th>
              <th class="has-text-right">
              {{postings.total_bal - postings.total_pdcs | currency('') }}
              </th>
            </tr>
          </tbody>
        </table>
      </div>
    </div>
  </section>

</template>
<script>
import { mapState } from "vuex";
import Invoice from "@/components/Invoice.vue";

export default {
  name: "Customers",
  // components: { Invoice },
  computed: {
    ...mapState(["postings", "customers", "fin_years", "cur_fin_year"])
  },
  created: function() {},
  watch: {
    customers() {
      this.isFetching = false;
    }
  },
  methods: {
    getAsyncCustomers() {
      if (this.name === undefined) {
        return;
      }
      if (this.name.length > 5) {
        return;
      }
      this.data = [];
      this.isFetching = true;
      this.$store.dispatch("GET_CUSTOMERS", this.name);
    },
    fetchSelectedCustomer: function(option) {
      if (option && option.id) {
        this.selected = option;
        let payload = { id: option.id, year: this.year };
        this.$store.dispatch("GET_POSTINGS", payload);
      }
    },
    yearChanged: function(option) {
      if (this.selected) {
        let payload = { id: this.selected.id, year: option };
        this.$store.dispatch("GET_POSTINGS", payload);
      }
    }
  },
  data() {
    return {
      name: "",
      selected: null,
      isFetching: false,
      year: 2018
    };
  }
};
</script>
<style scoped lang="scss">
.table td,
.table th {
  border: none;
}
tr.underline {
  border-bottom: 1px solid grey;
}
tr.overline {
  border-top: 1px solid grey;
}
</style>

// assets/js/Customers.svelte
<script>
  import { moneyFmt, dateFmt, FIN_YEARS } from './utils.js'
  import Autocomplete from './components/AutoComplete.svelte'
  import Invoice from './components/Invoice.svelte'
  import Modal from './components/Modal.svelte'

  export let handleEvent, pushEvent;
  let text = ''
  let year = FIN_YEARS[0]
  let selected = null
  let total = 0
  let isModalOpen = false
  let customers, postings = []
  let invoice_id = null

  $: if (text.length >= 2 && text.length <= 12) { pushEvent('get_customers', {query: text}) }

  handleEvent('get_postings', (payload) => { postings = payload.postings })
  handleEvent('get_customers', (payload) => { customers = payload.customers })

  function handleSelect(o) {
    selected = o.detail
    text = selected.description
    pushEvent('get_postings', {id: selected.id, year: year})
  }

  function yearChanged() {
    if (selected) pushEvent('get_postings', {id: selected.id, year: year})
  }

  function fetchInvoice(id) {
    invoice_id = id
    pushEvent('get_invoice', {id: id})
    isModalOpen = true
  }
</script>

<section class="wrapper flex gap-1 items-center">
    <Autocomplete
      id='customer'
      labelName='Find Customers: '
      placeholder='e.g. 37 Chemists'
      bind:value={text}
      on:select={handleSelect}
      data={customers} let:item={item}>
      <div class="flex flex-start px-4 py-2">
        <div class="flex-auto text-sm sm:overflow-x-auto">
          { item.description }
          <br>
          <small class="text-xs pt">
            <b>{ item.id }</b>,
            <b>{ item.region }</b>,
            <b>{ item.is_gov }</b>
          </small>
        </div>
      </div>
    </Autocomplete>
    <select bind:value={year} on:blur="{yearChanged}">
      {#each FIN_YEARS as y}
        <option>{y}</option>
      {/each}
    </select>
</section>
{#if (postings.id !== undefined)}
<section class="wrapper pt-2">
  <h1 class="title text-3xl">{postings.description}</h1>
  <div class="tags">
    <span class="tag">{postings.id}</span>
    <span class="tag">{postings.region}</span>
    <span class="tag">{postings.is_gov}</span>
    <span class="tag">{postings.resp}</span>
  </div>
  <h1 class="text-right pb-3 pr-2">
    <span class="subtitle pr-2">Opening Bal:</span>
    <span class="title text-lg font-semibold"> { moneyFmt(postings.op_bal) }</span>
  </h1>
  <table class="table w-full">
    <thead>
      <tr class="border-b border-gray-700" style="background-color: white;">
        <th class="text-left">ID</th>
        <th>Date</th>
        <th class="text-left">Description</th>
        <th class="text-right">Debit</th>
        <th class="text-right">Credit</th>
        <th class="text-right">Balance</th>
      </tr>
    </thead>
    <tbody>
      {#each postings.postings as t (t.id)}
      <tr>
        <td>
            {#if t.id.startsWith('S') }
            { t.id }
            {:else}
            { t.id.substring(9, t.id.length) }
            {/if}
        </td>
        <td class="text-center">{ dateFmt(t.date) }</td>
        <td>
          {#if t.description.startsWith('M ') || t.description.startsWith('C ')}
          <a on:click="{() => fetchInvoice(t.description)}" href="#{t.description}">
            { t.description }
          </a>
          {:else}
          { t.description }
          {/if}
        </td>
        <td class="text-right">{ moneyFmt(t.debit) }</td>
        <td class="text-right">{ moneyFmt(t.credit) }</td>
        <td class="text-right">{ moneyFmt(t.bal) }</td>
      </tr>
      {/each}
      <tr class="border-b border-t border-gray-700">
        <th></th>
        <th></th>
        <th class="text-right">Total:</th>
        <th class="text-right">{ moneyFmt(postings.total_debit) }</th>
        <th class="text-right">{ moneyFmt(postings.total_credit) }</th>
        <th class="text-right">{ moneyFmt(postings.total_bal) }</th>
      </tr>
      <tr></tr>
      {#if postings.total_pdcs > 0 }
      <tr class="border-b">
        <th>PDCS</th>
        <td></td>
        <td></td>
        <td></td>
        <td></td>
        <td></td>
      </tr>
      {#each postings.pdcs as p (p.id) }
      <tr>
        <td>{ p.id }</td>
        <td>{ dateFmt(p.date) }</td>
        <td>{ p.cheque }</td>
        <td></td>
        <td class="text-right">{ moneyFmt(p.amount) }</td>
        <td></td>
      </tr>
      {/each}
      <tr class="border-b border-t border-gray-700">
        <td></td>
        <td></td>
        <th class="text-right">Total:</th>
        <th class="text-right"></th>
        <th class="text-right">{ moneyFmt(postings.total_pdcs) }</th>
        <th class="text-right">
          { moneyFmt(postings.total_bal - postings.total_pdcs) }
        </th>
      </tr>
      {/if}
    </tbody>
  </table>
</section>
{/if}
<Modal open={isModalOpen}>
  <Invoice handleEvent={handleEvent}/>
</Modal>
