// assets/src/views/Customers.vue
<template>
  <section class="section">
    <div class="container">
      <BField>
        <p class="control">
          <button class="button is-static">
            Search Customer
          </button>
        </p>
        <BAutocomplete
          expanded
          v-model="name"
          :data="customers"
          placeholder="e.g. 37 Chemists"
          autofocus
          icon="person"
          field="description"
          :loading="isFetching"
          @input="getAsyncCustomers"
          @select="option => fetchSelectedCustomer(option)"
          >
          <template slot-scope="props">
            <div class="media">
              <div class="media-content">
                {{ props.option.description }}
                <br>
                <small>
                  <b>{{ props.option.id }}</b>,
                  <b>{{ props.option.region }}</b>,
                  <b>{{ props.option.is_gov }}</b>,
                  <b>{{ props.option.resp }}</b>
                </small>
              </div>
            </div>
          </template>
          <template slot="empty">No results found</template>
        </BAutocomplete>
        <BSelect placeholder="Fin Year" v-model="year" @input="yearChanged">
          <option
            v-for="option in fin_years"
            :value="option"
            :key=option>
          {{option}}
          </option>
        </BSelect>
      </BField>
    </div>

    <div v-if="postings.op_bal != null" class="section" style="padding-top: 1rem; padding-bottom: 1rem;">
      <div class="container">
        <div class="columns">
          <div class="column">
            <h1 class="title">
              {{postings.description}}
            </h1>
            <h2 class="subtitle">
              <BTaglist>
                <BTag>{{postings.id}}</BTag>
                <BTag>{{postings.region}}</BTag>
                <BTag>{{postings.is_gov}}</BTag>
                <BTag>{{postings.resp}}</BTag>
              </BTaglist>
            </h2>
          </div>
        </div>
        <table class="table is-narrow is-fullwidth is-hoverable">
          <tbody>
            <tr>
              <td></td>
              <td></td>
              <td></td>
              <td></td>
              <th class="has-text-right">Opening Bal:</th>
              <th class="has-text-right">{{postings.op_bal | currency('')}}</th>
            </tr>
            <tr>
              <td></td>
              <td></td>
              <td></td>
              <td></td>
              <td></td>
              <td></td>
            </tr>
            <tr class="underline">
              <th>ID</th>
              <th>Date</th>
              <th>Description</th>
              <th class="has-text-right">Debit</th>
              <th class="has-text-right">Credit</th>
              <th class="has-text-right">Balance</th>
            </tr>
            <tr v-for="p in postings.postings" :key="p.id">
              <td>
                <span v-if="p.id.startsWith('S')">{{p.id}}</span>
                <span v-else>{{p.id.substring(8, p.id.length)}}</span>
              </td>
              <td>{{p.date}}</td>
              <td>{{p.description}}</td>
              <td class="has-text-right">{{p.debit | currency('')}}</td>
              <td class="has-text-right">{{p.credit | currency('')}}</td>
              <td class="has-text-right">{{p.bal | currency('')}}</td>
            </tr>
            <tr class="underline overline">
              <td></td>
              <td></td>
              <th class="has-text-right">Total: </th>
              <th class="has-text-right">{{postings.total_debit | currency('')}}</th>
              <th class="has-text-right">{{postings.total_credit | currency('')}}</th>
              <th class="has-text-right">
              {{postings.total_bal | currency('') }}
              </th>
            </tr>
            <tr>
              <td></td>
              <td></td>
              <td></td>
              <td></td>
              <td></td>
              <td></td>
            </tr>
            <tr class="underline" v-if="postings.total_pdcs > 0">
              <th>PDCS</th>
              <td></td>
              <td></td>
              <td></td>
              <td></td>
              <td></td>
            </tr>
            <tr v-for="p in postings.pdcs" :key="p.id">
              <td>{{p.id}}</td>
              <td>{{p.date}}</td>
              <td>{{p.cheque}}</td>
              <td></td>
              <td class="has-text-right">{{p.amount | currency('')}}</td>
              <td></td>
            </tr>
            <tr class="underline overline" v-if="postings.total_pdcs > 0">
              <td></td>
              <td></td>
              <th class="has-text-right">Total: </th>
              <th class="has-text-right"></th>
              <th class="has-text-right">{{postings.total_pdcs | currency('')}}</th>
              <th class="has-text-right">
              {{postings.total_bal - postings.total_pdcs | currency('') }}
              </th>
            </tr>
          </tbody>
        </table>
      </div>
    </div>
  </section>

</template>
<script>
import { mapState } from "vuex";
import Invoice from "@/components/Invoice.vue";

export default {
  name: "Customers",
  // components: { Invoice },
  computed: {
    ...mapState(["postings", "customers", "fin_years", "cur_fin_year"])
  },
  created: function() {},
  watch: {
    customers() {
      this.isFetching = false;
    }
  },
  methods: {
    getAsyncCustomers() {
      if (this.name === undefined) {
        return;
      }
      if (this.name.length > 5) {
        return;
      }
      this.data = [];
      this.isFetching = true;
      this.$store.dispatch("GET_CUSTOMERS", this.name);
    },
    fetchSelectedCustomer: function(option) {
      if (option && option.id) {
        this.selected = option;
        let payload = { id: option.id, year: this.year };
        this.$store.dispatch("GET_POSTINGS", payload);
      }
    },
    yearChanged: function(option) {
      if (this.selected) {
        let payload = { id: this.selected.id, year: option };
        this.$store.dispatch("GET_POSTINGS", payload);
      }
    }
  },
  data() {
    return {
      name: "",
      selected: null,
      isFetching: false,
      year: 2018
    };
  }
};
</script>
<style scoped lang="scss">
.table td,
.table th {
  border: none;
}
tr.underline {
  border-bottom: 1px solid grey;
}
tr.overline {
  border-top: 1px solid grey;
}
</style>

// assets/js/pages/Customers.svelte
<!-- on:keyup={debounce(suggestCustomers, 150)} -->
<section class="section has-small-padding">
  <div class="container">
    <div class="field is-horizontal has-addons">
      <p class="control">
        <button class="button is-static">
        Search Customer
        </button>
      </p>
      <Autocomplete
        id='customer'
        placeholder='e.g. 37 Chemists'
        className='input is-fullwidth'
        bind:value={text}
        on:select={handleSelect}
        data={$customers} let:item={item}>
        <div class="media">
          <div class="media-content">
            { item.description }
            <br>
            <small>
              <b>{ item.id }</b>,
              <b>{ item.region }</b>,
              <b>{ item.is_gov }</b>
            </small>
          </div>
        </div>
      </Autocomplete>
      <div class="control">
        <div class="select">
          <select bind:value={year} on:change="{yearChanged}">
            {#each $fin_years as y}
              <option>{y}</option>
            {/each}
          </select>
        </div>
      </div>
    </div>
  </div>
</section>
{#if ($postings.id !== undefined)}
<div class="section">
<div class="container">
    <div class="columns">
      <div class="column">
          <h1 class="title has-small-margin-bottom">{$postings.description}</h1>
          <div class="tags">
            <span class="tag">{$postings.id}</span>
            <span class="tag">{$postings.region}</span>
            <span class="tag">{$postings.is_gov}</span>
            <span class="tag">{$postings.resp}</span>
          </div>
      </div>
    </div>
    <table class="table is-narrow is-fullwidth is-hoverable">
      <tbody>
        <tr>
          <th></th>
          <th></th>
          <th></th>
          <th></th>
          <th class="has-text-right">Opening Bal:</th>
          <th class="has-text-right">
            { currencyFormat($postings.op_bal) }
          </th>
        </tr>
        <tr>
          <td></td>
          <td></td>
          <td></td>
          <td></td>
          <td></td>
          <td></td>
        </tr>
        <tr class="has-underline">
          <th>ID</th>
          <th>Date</th>
          <th>Description</th>
          <th class="has-text-right">Debit</th>
          <th class="has-text-right">Credit</th>
          <th class="has-text-right">Balance</th>
        </tr>
        {#each $postings.postings as t (t.id)}
        <tr>
          <td>
              {#if t.id.startsWith('S') }
              { t.id }
              {:else}
              { t.id.substring(9, t.id.length) }
              {/if}
          </td>
          <td>{ dateFormat(t.date) }</td>
          <td>
            {#if t.description.startsWith('M ') || t.description.startsWith('C ')}
            <a on:click="{() => fetchInvoice(t.description)}" href="#{t.description}">
              { t.description }
            </a>
            {:else}
            { t.description }
            {/if}
          </td>
          <td class="has-text-right" on:click="{() => addCell(t.debit)}">{ currencyFormat(t.debit) }</td>
          <td class="has-text-right" on:click="{() => addCell(-t.credit)}">{ currencyFormat(t.credit) }</td>
          <td class="has-text-right" on:click="{resetCell}">{ currencyFormat(t.bal) }</td>
        </tr>
        {/each}
        <tr class="has-underline has-overline">
          <th></th>
          <th></th>
          <th class="has-text-right">Total:</th>
          <th class="has-text-right">{ currencyFormat($postings.total_debit) }</th>
          <th class="has-text-right">{ currencyFormat($postings.total_credit) }</th>
          <th class="has-text-right">{ currencyFormat($postings.total_bal) }</th>
        </tr>
        <tr></tr>
        {#if $postings.total_pdcs > 0 }
        <tr class="has-underline">
          <th>PDCS</th>
          <td></td>
          <td></td>
          <td></td>
          <td></td>
          <td></td>
        </tr>
        {#each $postings.pdcs as p (p.id) }
        <tr>
          <td>{ p.id }</td>
          <td>{ dateFormat(p.date) }</td>
          <td>{ p.cheque }</td>
          <td></td>
          <td class="has-text-right">{ currencyFormat(p.amount) }</td>
          <td></td>
        </tr>
        {/each}
        <tr class="has-underline has-overline">
          <td></td>
          <td></td>
          <th class="has-text-right">Total:</th>
          <th class="has-text-right"></th>
          <th class="has-text-right">{ currencyFormat($postings.total_pdcs) }</th>
          <th class="has-text-right">
            { currencyFormat($postings.total_bal - $postings.total_pdcs) }
          </th>
        </tr>
        {/if}
      </tbody>
    </table>
</div>
</div>
{/if}
<div class="modal" class:is-active="{isModalOpen}">
  <div class="modal-background" on:click="{() => isModalOpen = false}"></div>
  <div class="modal-content">
    <Invoice/>
  </div>
  <button on:click="{() => isModalOpen = false}"
    class="modal-close is-large" aria-label="close"></button>
</div>

<script>
  import { invoice } from '../stores/invoice.js'
  import { postings } from '../stores/postings.js'
  import { customers } from '../stores/customers.js'
  import { fin_years } from '../stores/fin_years.js'
  import { currencyFormat, dateFormat } from '../utils/utils.js'
  import Autocomplete from '../components/Autocomplete.svelte'
  import Invoice from '../components/Invoice.svelte'
  import { toast } from '../../node_modules/bulma-toast/src/index.js'

  let text = ''
  let year = 2018
  let selected = null
  let total = 0
  let isModalOpen = false

  $: if (text.length >= 2 && text.length <= 12) {
    customers.fetch(text)
  }

  function handleSelect(o) {
    selected = o.detail
    text = selected.description
    postings.fetch(selected.id, year)
  }

  function yearChanged() {
    if (selected) {
      postings.fetch(selected.id, year)
    }
  }

  function addCell(value) {
    total += value
    toast({
      message: `Total: ${ currencyFormat(total) }`,
      position: 'bottom-center',
      closeOnClick: true,
      pauseOnHover: true,
      duration: 5000
    })
  }

  function resetCell() { 
    total = 0
    toast({
      message: `Total: ${ currencyFormat(total) }`,
      position: 'bottom-center',
      closeOnClick: true,
      pauseOnHover: true,
      duration: 7000
    })
  }

  function fetchInvoice(id) {
    invoice.fetch(id)
    isModalOpen = true
  }

</script>

<style>
th, td { border: none; }
</style>
