// assets/src/views/Invoices.vue
<template>
  <section class="section">
    <div class="container">
      <b-field>
        <p class="control">
          <button class="button is-static">Search for Invoice:</button>
        </p>
        <b-autocomplete
          expanded
          v-model="search"
          :data="data"
          placeholder="e.g. 95632"
          field="id"
          :loading="isFetching"
          :max-results="12"
          :maxlength="10"
          @input="suggestInvoiceIds"
          @select="option => fetchSelectedInvoice(option.id)"
        >
          <template slot-scope="props">
            <div class="media">
              <div class="media-left">
                <img width="32" />
              </div>
              <div class="media-content">
                {{ props.option.id }}
                <br />
                <small>
                  Customer ID: <b>{{ props.option.customer_id }}</b
                  >, Date: <b>{{ props.option.date }}</b>
                </small>
              </div>
            </div>
          </template>
          <template slot="empty"
            >No results found</template
          >
        </b-autocomplete>
      </b-field>
    </div>

    <Invoice></Invoice>
  </section>
</template>

<script>
import { mapState } from "vuex";
import Invoice from "@/components/Invoice.vue";

export default {
  name: "Invoices",
  components: {
    Invoice
  },
  computed: {
    ...mapState({
      invoiceIds: state => state.invoice_ids
    })
  },
  watch: {
    invoiceIds() {
      this.isFetching = false;
      this.data = this.invoiceIds;
    }
  },
  methods: {
    suggestInvoiceIds() {
      if (this.search === undefined) {
        return;
      }
      if (this.search < 3) {
        return;
      }
      this.data = [];
      this.isFetching = true;
      this.$store.dispatch("GET_INVOICES", this.search);
    },
    fetchSelectedInvoice(invoice_id) {
      this.$store.dispatch("GET_INVOICE", invoice_id);
    }
  },
  data() {
    return {
      search: "",
      invoice: "",
      data: [],
      selected: null,
      isFetching: false
    };
  }
};
</script>

<style></style>

// assets/js/pages/Invoices.svelte
<section class="section">
  <div class="container">
    <div class="field is-horizontal has-addons">
      <p class="control">
        <button class="button is-static">
        Search Invoices
        </button>
      </p>
      <Autocomplete
        id='invoice'
        placeholder='e.g. 32521'
        className='input is-fullwidth'
        bind:value={text}
        on:select={handleSelect}
        data={$invoices} let:item={item}>
        <div class="media">
          <div class="media-content">
            { item.id }
            <br>
            <small>
              <b>{ item.date }</b>,
              <b>{ item.customer_id }</b>
            </small>
          </div>
        </div>
      </Autocomplete>
    </div>
  </div>
</section>
<section class="section">
  <Invoice/>
</section>


<script>
  import { invoice } from '../stores/invoice.js';
  import { invoices } from '../stores/invoices.js';
  import Autocomplete from '../components/Autocomplete.svelte';
  import Invoice from '../components/Invoice.svelte';

  let text = ''
  let selected = null

  $: if (text.length >= 2 && text.length <= 12) {
    invoices.fetch(text)
  }

  function handleSelect(o) {
    selected = o.detail
    text = selected.id
    invoice.fetch(selected.id)
  }
</script>
