// assets/src/views/Sales.vue
<template>
  <section class="section">
    <div class="container">
      <b-tabs v-model="activeTab">
        <b-tab-item label="Daily" class="adjust-padding">
          <DailySales/>
        </b-tab-item>

        <b-tab-item label="Monthly">
          <MonthlySales/>
        </b-tab-item>

        <b-tab-item label="Yearly">
          <YearlySales/>
        </b-tab-item>

      </b-tabs>
    </div>
  </section>
</template>

<script>
import DailySales from "@/components/DailySales.vue";
import MonthlySales from "@/components/MonthlySales.vue";
import YearlySales from "@/components/YearlySales.vue";

export default {
  name: "Sales",
  components: {
    DailySales,
    MonthlySales,
    YearlySales
  },
  data() {
    return {
      activeTab: 0
    };
  }
};
</script>
<style scoped lang="scss">
.tab-item {
  min-height: 420px;
}
</style>

// assets/js/pages/Sales.svelte
<script>
  import DailySales from '../components/DailySales.svelte'
  import MonthlySales from '../components/MonthlySales.svelte'
  import YearlySales from '../components/YearlySales.svelte'

  export let tab

</script>

<section class="section">
  <div class="container">
    <div class="tabs">
      <ul>
        <li class:is-active="{tab != 'monthly' && tab != 'yearly' }"><a href="/sales/daily">Daily</a></li>
        <li class:is-active="{tab == 'monthly'}"><a href="/sales/monthly">Monthly</a></li>
        <li class:is-active="{tab == 'yearly'}"><a href="/sales/yearly">Yearly</a></li>
      </ul>
    </div>
  </div>
</section>
{#if tab && tab == 'monthly'}
<MonthlySales/>
{:else if tab && tab == 'yearly'}
<YearlySales/>
{:else }
<DailySales/>
{/if}
