// assets/js/components/MonthlySales.svelte
<section class="section">
  <div class="container">
      <div class="field is-horizontal has-addons is-pulled-right">
          <p class="control">
            <button class="button is-static">
            Month | Year 
            </button>
          </p>
          <div class="control">
              <div class="select">
                <select bind:value={month} on:change="{monthChanged}">
                  {#each MONTHS as m}
                    <option>{m}</option>
                  {/each}
                </select>
              </div>
            </div>
          <div class="control">
            <div class="select">
              <select bind:value={year} on:change="{yearChanged}">
                {#each CUR_YEARS as y}
                  <option>{y}</option>
                {/each}
              </select>
            </div>
          </div>
        </div>
        <table class="table is-bordered is-narrow is-fullwidth is-hoverable is-striped">
      <thead>
        <tr>
          <th class="has-text-centered">Month</th>
          <th class="has-text-centered">Local</th>
          <th class="has-text-centered">Imported</th>
          <th class="has-text-centered">Total</th>
        </tr>
      </thead>
      <tbody>
        {#each $sales.monthly as s }
        <tr>
          <td class="has-text-centered">{ dateFormat(s.date        ) }</td>
          <td class="has-text-right">   { currencyFormat(s.local   ) }</td>
          <td class="has-text-right">   { currencyFormat(s.imported) }</td>
          <td class="has-text-right">   { currencyFormat(s.total   ) }</td>
        </tr>
        {/each}
      </tbody>
      <tfoot>
        <tr>
          <th class="has-text-right">Total:</th>
          <th class="has-text-right">{ currencyFormat(localTotal   ) }</th>
          <th class="has-text-right">{ currencyFormat(importedTotal) }</th>
          <th class="has-text-right">{ currencyFormat(total        ) }</th>
        </tr>
      </tfoot>
    </table>
  </div>
</section>


<script>
  import { MONTHS, CUR_YEARS, CUR_YEAR, CUR_MONTH } from '../stores/constants.js'
  import { sales   } from '../stores/sales.js'
  import { currencyFormat, dateFormat } from '../utils/utils.js'
  import { onMount } from 'svelte'

  let year          = CUR_YEAR
  let month         = CUR_MONTH
  let localTotal    = 0
  let importedTotal = 0
  let total         = 0

  $: if ($sales.monthly) {
    localTotal    = 0.00
    importedTotal = 0.00
    total         = 0.00
    $sales.monthly.forEach(i => {
      localTotal    += i.local
      importedTotal += i.imported
      total         += i.total
    })
  }

  onMount(() => {
    sales.getMonthlySales(year, month)
  })

  function yearChanged() {
    sales.getMonthlySales(year, month)
  }

  function monthChanged() {
    sales.getMonthlySales(year, month)
  }
</script>

// assets/src/components/MonthlySales.vue
<template>
  <div>
    <div class="field is-grouped">
      <div class="control">
        <div class="select">
          <select v-model="year" @change="getMonthlySales()">
            <option v-for="y in cur_years" :key="y" :value="y">{{ y }}</option>
          </select>
        </div>
      </div>
      <span>-&nbsp;&nbsp;</span>
      <div class="control">
        <div class="select">
          <select v-model="month" @change="getMonthlySales()">
            <option v-for="m in months_array" :key="m" :value="m">{{
              m
            }}</option>
          </select>
        </div>
      </div>
    </div>
    <table
      class="table is-bordered is-narrow is-fullwidth is-hoverable is-striped"
    >
      <thead>
        <tr>
          <th class="has-text-centered">Date</th>
          <th class="has-text-centered">Local</th>
          <th class="has-text-centered">Imported</th>
          <th class="has-text-centered">Total</th>
        </tr>
      </thead>
      <tbody>
        <tr v-for="s in monthly_sales" :key="s.date">
          <td class="has-text-centered">{{ s.date }}</td>
          <td class="has-text-right">{{ s.local | currency("") }}</td>
          <td class="has-text-right">{{ s.imported | currency("") }}</td>
          <td class="has-text-right">{{ s.total | currency("") }}</td>
        </tr>
      </tbody>
      <tfoot>
        <tr>
          <th class="has-text-right">Total:</th>
          <th class="has-text-right">
            {{ this.summary.local | currency("") }}
          </th>
          <th class="has-text-right">
            {{ this.summary.imported | currency("") }}
          </th>
          <th class="has-text-right">
            {{ this.summary.total | currency("") }}
          </th>
        </tr>
      </tfoot>
    </table>
  </div>
</template>

<script>
import { mapState } from "vuex";

export default {
  name: "MonthlySales",
  created() {
    if (!this.month) {
      this.month = this.cur_month;
    }
    if (!this.year) {
      this.year = this.cur_year;
    }
    this.getMonthlySales();
  },
  computed: {
    summary: function() {
      let data = {
        total: 0,
        local: 0,
        imported: 0
      };
      this.monthly_sales.forEach(function(x) {
        data.local += x.local;
        data.imported += x.imported;
      });
      data.total = data.local + data.imported;
      return data;
    },
    ...mapState([
      "monthly_sales",
      "cur_years",
      "months_array",
      "cur_month",
      "cur_year"
    ])
  },
  methods: {
    getMonthlySales() {
      this.$store.dispatch("GET_MONTHLY_SALES", {
        year: Number(this.year),
        month: Number(this.month)
      });
    }
  },
  data() {
    return {
      year: null,
      month: null
    };
  }
};
</script>
